version: "3.8"
services:
  app:
    container_name: express-mongo
    restart: always
    build: .
    # env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - "80:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    logging:
      driver: "none"

volumes:
  node_modules:
  mongodata:
